
COMMENT_ILA_DEFINITION = "@ADD_ILA"
COMMENT_BEGINNING_SECTION = f"// AUTOGENERATED FROM '{COMMENT_ILA_DEFINITION}' definitions. Please add clock signal below!"

class Token():

    def __init__(self, kind, text):
        self.kind = kind
        self.text = text

    def __str__(self):
        return f"Token {{.kind = '{self.kind}', .text = '{self.text}'}}"

    @staticmethod
    def from_raw_token(raw_token):
        assert "tag" in raw_token, f"Found raw token with invalid tag: {raw_token}"
        return Token(raw_token["tag"], raw_token["text"] if "text" in raw_token else "")

    def is_symbol_identifier(self):
        return self.kind == "SymbolIdentifier"
    
    def is_ila_definition_token(self):
        return self.kind == "TK_EOL_COMMENT" and COMMENT_ILA_DEFINITION.lower() in self.text.lower() and (not self.is_own_generated_comment())
    
    def is_white_space_token(self):
        return self.kind in ["TK_EOL_COMMENT", "TK_NEWLINE", "TK_SPACE"]
    
    def is_line_end_token(self):
        return self.kind in [",", ";"]

    def self_kind_is(self, text):
        return self.kind == text
    
    def is_own_generated_comment(self):
        return self.text == COMMENT_BEGINNING_SECTION

    def text_equals(self, text):
        return self.text == text
    
    def get_text(self):
        return self.text