#!/usr/bin/env python3
# vi: set ft=python

from io import BufferedReader
from pyarrow.parquet import ParquetFile
from thrift.transport import TTransport
from thrift.protocol import TCompactProtocol
import sys
import traceback

from metadata import Page, ColumnChunk, Encoding, Compression, Type, RowGroup, Metadata, String
# This file has been generated with the thirft compiler from the parquet header
# definition files
from ttypes import PageHeader

HEADER_MAX_SIZE = 128

def parse_encoding(raw: int) -> Encoding:
    match raw:
        case 0:
            return Encoding.PLAIN
        case 2 | 8:
            return Encoding.HYBRID

    raise Exception(f'unsupported encoding: {raw}, only 0 (PLAIN) and 8 (HYBRID) are supported')

def parse_compression(raw: str) -> Compression:
    match raw:
        case 'SNAPPY':
            return Compression.SNAPPY
        case 'UNCOMPRESSED':
            return Compression.RAW

    raise Exception(f'unsupported compression: {raw}, only SNAPPY and UNCOMPRESSED are supported')

def parse_type(raw: str) -> Type:
    match raw:
        case 'BYTE' | 'BOOL':
            return Type.BYTE
        case 'INT32':
            return Type.INT32
        case 'INT64':
            return Type.INT64
        case 'FLOAT':
            return Type.FLOAT
        case 'DOUBLE':
            return Type.DOUBLE
        case 'BYTE_ARRAY':
            return Type.BYTE_ARRAY

    raise Exception(f'unsupported type: {raw}')

def read_page(f: BufferedReader, pos: int, max_sz: int, is_dictionary: bool) -> tuple[Page, int]:
    pos = f.seek(pos)
    if pos != pos:
        raise Exception(f"attempted to seek to {pos}, only got to {pos}")

    # We read the whole page in memory to then use TMemoryBuffer and thus be
    # able to tell how big the page is. We could use a TFileTransport instead,
    # but that includes buffering (+ python has its own buffering on `File`s),
    # so the readnig would not be accurate.
    data = f.read(min(max_sz, HEADER_MAX_SIZE))
    transport = TTransport.TMemoryBuffer(data)
    protocol = TCompactProtocol.TCompactProtocol(transport)

    header = PageHeader()
    header.read(protocol)
    header_size = transport._buffer.tell()

    pos = pos + header_size
    sz = header.compressed_page_size
    bytes_read = sz + header_size

    if is_dictionary:
        num_values = 0
    else:
        if header.data_page_header is None:
            raise Exception(f"header for page at {pos}+:{sz} is missing field `data_page_header`, required to extract the number of values in this page")

        num_values = int(header.data_page_header.num_values)

    if header.dictionary_page_header is not None:
        raw_encoding = header.dictionary_page_header.encoding
    elif header.data_page_header is not None:
        raw_encoding = header.data_page_header.encoding
    else:
        raise Exception(f"header for page at {pos}+:{sz} is not supported (value: {header}). only dictionary or datav1 pages are supported")

    encoding = parse_encoding(raw_encoding)
    return Page(encoding=encoding, offset=pos, size=sz, num_values=num_values), bytes_read

def collect_data_pages(f: BufferedReader, pos: int, sz: int, num_values: int) -> list[Page]:
    vals = 0
    pages: list[Page] = []

    while vals < num_values:
        page, rd = read_page(f, pos, sz, False)
        pages.append(page)

        vals += page.num_values
        pos += rd
        sz -= rd

    assert sz == 0

    return pages

def are_pages_ordered(pages: list[Page]) -> bool:
    plain_seen = False

    for page in pages:
        if page.encoding == Encoding.PLAIN:
            plain_seen = True
        elif page.encoding == Encoding.HYBRID and plain_seen:
            return False

    return True

def count_hybrid_values(pages: list[Page]) -> int:
    count = False

    for page in pages:
        if page.encoding == Encoding.HYBRID:
            count += page.num_values

    return count

def main(file: str):
    try:
        pf = ParquetFile(file)
        f = open(file, "rb")
    except Exception as e:
        raise Exception(f"could not open {file} to read as binary: {e}")

    column_names = [String(s) for s in pf.schema_arrow.names]

    row_groups = []
    for i in range(pf.metadata.num_row_groups):
        chunks = []
        for j in range(pf.metadata.num_columns):
            col_meta = pf.metadata.row_group(i).column(j)
            compression = parse_compression(col_meta.compression)

            dict_sz = 0
            if col_meta.has_dictionary_page:
                pos = col_meta.dictionary_page_offset
                dict_sz = col_meta.data_page_offset - col_meta.dictionary_page_offset
                dict, bytes_read = read_page(f, pos, dict_sz, True)
                assert bytes_read == dict_sz

            pos = col_meta.data_page_offset
            max_sz = col_meta.total_compressed_size - dict_sz
            data_pages = collect_data_pages(f, pos, max_sz, col_meta.num_values)

            compression_ratio = col_meta.total_uncompressed_size / col_meta.total_compressed_size
            print(f"{i}:{j}:compression = {compression_ratio}")

            if not are_pages_ordered(data_pages):
                raise Exception(f"column chunk {i}:{j} contains data pages that are not ordered (namely, HYBRID,...,HYBRID,PLAIN,...,PLAIN)")
            hybrid_num_values = count_hybrid_values(data_pages)

            typ = parse_type(col_meta.physical_type)
            chunk = ColumnChunk(
                type=typ,
                num_values=col_meta.num_values,
                hybrid_num_values=hybrid_num_values,
                compression=compression,
                dictionary=dict if col_meta.has_dictionary_page else None,
                data=tuple(data_pages),
            )
            chunks.append(chunk)

        rg = RowGroup(chunks=tuple(chunks))
        row_groups.append(rg)

    meta = Metadata(column_names=tuple(column_names), groups=tuple(row_groups))

    out_file = f"{file}.meta"
    try:
        f = open(out_file, "wb")
    except Exception as e:
        raise Exception(f"could not open {out_file} to write as binary: {e}")

    try:
        meta.to_file(f)
        f.flush()
    except Exception as e:
        raise Exception(f"could not write metadata to {out_file}: {e}")

    try:
        f = open(out_file, "rb")
        written_meta = Metadata.from_file(f)
    except Exception as e:
        raise Exception(f"error while reading written meta to check if it matches: {e}")

    assert written_meta == meta

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"usage: {sys.argv[0]} <file.parquet>", file=sys.stderr)
        sys.exit(1)

    file = sys.argv[1]
    try:
        main(file)
    except Exception:
        print(f"could not parse file {file}: {traceback.format_exc()}", file=sys.stderr)
        sys.exit(2)
