#!/usr/bin/env python3
# vi: set ft=python

import sys
from metadata import Metadata

def main(file: str):
    try:
        f = open(file, "rb")
        meta = Metadata.from_file(f)
    except Exception as e:
        print(f"could not read metadata from {file}: {e}", file=sys.stderr)
        sys.exit(1)

    for i, name_str in enumerate(meta.column_names):
        print(f'{i}: {name_str.value}')

    for i, rg in enumerate(meta.groups):
      for j, chunk in enumerate(rg.chunks):
        print(f'{i}:{j} {chunk.num_values} {chunk.hybrid_num_values} {str(chunk.type)} {str(chunk.compression)}')

        if chunk.dictionary is not None:
          page = chunk.dictionary
          print(f'{i}:{j}:dict {page.offset} {page.size} {str(page.encoding)}')

        for k, page in enumerate(chunk.data):
            print(f'{i}:{j}:data:{k} {page.offset} {page.size} {str(page.encoding)} {page.num_values}')


if len(sys.argv) < 2:
    print(f"usage: {sys.argv[0]} <file.parquet.meta>", file=sys.stderr)
    sys.exit(1)

main(sys.argv[1])
