#!/usr/bin/env python3
# vi: set ft=python

import sys
from metadata import Metadata, Encoding

def main(file: str):
    try:
        f = open(file, "rb")
        meta = Metadata.from_file(f)
    except Exception as e:
        print(f"could not read metadata from {file}: {e}", file=sys.stderr)
        sys.exit(1)

    for i, name_str in enumerate(meta.column_names):
        print(f'{i}: {name_str.value}')

    for i, rg in enumerate(meta.groups):
      for j, chunk in enumerate(rg.chunks):
        total_bytes = chunk.num_values * chunk.type.size()
        plain_bytes = 0

        if chunk.dictionary is not None:
          page = chunk.dictionary
          plain_bytes += page.size

        for k, page in enumerate(chunk.data):
            plain_bytes += page.size

        percentage = "{:.2f}".format(plain_bytes/total_bytes)
        print(f"{i},{j},{total_bytes},{plain_bytes},{percentage}")


if len(sys.argv) < 2:
    print(f"usage: {sys.argv[0]} <file.parquet.meta>", file=sys.stderr)
    sys.exit(1)

main(sys.argv[1])
